### ISSUE TITLE
Doesn't work on Ubuntu 14.10

### ISSUE THREAD

**Issue by vjdhama** [jonalmeida/UberWriter#2]
The background is not at all there.

![uberwriter](https://cloud.githubusercontent.com/assets/2221174/5270302/d4a73586-7a8f-11e4-950b-8bdf1343f2cb.png)

**Comment by jonalmeida** [comment]
Thanks for logging this! I'll have a look at it today/tomorrow.

P.S: We share the same Material Design wallpaper :smile:

**Comment by vjdhama** [comment]
I guess we do. :clap:

**Comment by jonalmeida** [comment]
Just realized this, but this build is specifically for non-Ubuntu debian builds so you should definitely check out Wolf's Ubuntu build.

**Comment by walterbak** [comment]
Hi, I've the same problem with ubuntu 14.10 unity. I've installed UberWriter with PPA. The version installed is uberwriter 14.09.08-publicubuntu5.
![uber-writer-background](https://cloud.githubusercontent.com/assets/6140879/7293943/781a6c28-e9a9-11e4-9482-a2976356ea36.png)

**Comment by jonalmeida** [comment]
This is not the official build of UberWriter that comes from the ppa. It's a modified version to get it to work on non-Ubuntu debian distros. The source for the official version from @wolfv can be found [here](https://github.com/wolfv/uberwriter). It may include fixes for the issue you mentioned (I haven't had the time to try it out).
