### ISSUE TITLE
Doesn't work on Ubuntu 14.10

### ISSUE THREAD

**Issue by walterbak** [jonalmeida/UberWriter#3]
Hi, I've the same problem reported by vjdama @ https://github.com/jonalmeida/UberWriter/issues/2 with ubuntu 14.10 unity. I've installed UberWriter with PPA. The version installed is uberwriter 14.09.08-publicubuntu5.
The background of working area is transparent.
![uber-writer-background](https://cloud.githubusercontent.com/assets/6140879/7297021/26c1ad48-e9c5-11e4-9997-224ccc5154a9.png)

**Comment by jonalmeida** [comment]
See comments here: https://github.com/jonalmeida/UberWriter/issues/2#issuecomment-95597264
